export default{
  'success': true,
  'errorDetail': null,
  'data': [
    {
      'appSystemId': '4302475966',
      'appSystemName': '门诊部管理',
      'appSystemPicUrl': null,
      'appSystemRelativeUri': 'web-adt-outpatient/index',
      'appMenuList': [
        {
          'appMenuId': '107627284824027136',
          'appMenuCode': '399205727',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '门诊患者管理',
          'appMenuList': [
            {
              'appMenuId': '107627493129940992',
              'appMenuCode': '399205747',
              'appMenuRelativeUri': '/web-adt-outpatient/office',
              'appMenuTypeCode': '256053',
              'appMenuName': '患者管理',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '107627256906739713',
          'appMenuCode': '399205726',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '门诊排班',
          'appMenuList': [
            {
              'appMenuId': '107627323478732801',
              'appMenuCode': '399205728',
              'appMenuRelativeUri': 'web-adt-outpatient/index',
              'appMenuTypeCode': '256053',
              'appMenuName': '首页',
              'appMenuList': []
            }, {
              'appMenuId': '107627357838471169',
              'appMenuCode': '399205729',
              'appMenuRelativeUri': 'web-adt-outpatient/scheduleView',
              'appMenuTypeCode': '256053',
              'appMenuName': '排班表',
              'appMenuList': []
            }, {
              'appMenuId': '107627396493176833',
              'appMenuCode': '399205744',
              'appMenuRelativeUri': 'web-adt-outpatient/schedulePlay',
              'appMenuTypeCode': '256053',
              'appMenuName': '周计划管理',
              'appMenuList': []
            }, {
              'appMenuId': '107627422262980608',
              'appMenuCode': '399205745',
              'appMenuRelativeUri': 'web-adt-outpatient/scheduleTeam',
              'appMenuTypeCode': '256053',
              'appMenuName': '协同排班',
              'appMenuList': []
            }, {
              'appMenuId': '107627448032784384',
              'appMenuCode': '399205746',
              'appMenuRelativeUri': 'web-adt-outpatient/scheduleSetting',
              'appMenuTypeCode': '256053',
              'appMenuName': '基础设置',
              'appMenuList': []
            }
          ]
        }
      ]
    }, {
      'appSystemId': '4300000015',
      'appSystemName': '主数据管理',
      'appSystemPicUrl': 'c:\\',
      'appSystemRelativeUri': 'web-admin-mdm-framework/#/master-data',
      'appMenuList': [
        {
          'appMenuId': '4302690568',
          'appMenuCode': '869468',
          'appMenuRelativeUri': 'mdm/#/guidePage',
          'appMenuTypeCode': '256053',
          'appMenuName': '流程向导',
          'appMenuList': []
        }, {
          'appMenuId': '4303244568',
          'appMenuCode': '959542',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '主数据',
          'appMenuList': [
            {
              'appMenuId': '4300000025',
              'appMenuCode': '256021',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '组织',
              'appMenuList': [
                {
                  'appMenuId': '4300000026',
                  'appMenuCode': '256022',
                  'appMenuRelativeUri': 'mdm/#/group',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '集团',
                  'appMenuList': []
                }, {
                  'appMenuId': '4300000027',
                  'appMenuCode': '256023',
                  'appMenuRelativeUri': 'mdm/#/hospital',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '医院',
                  'appMenuList': []
                }, {
                  'appMenuId': '4300000028',
                  'appMenuCode': '256024',
                  'appMenuRelativeUri': 'mdm/#/department',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '行政科室',
                  'appMenuList': []
                }, {
                  'appMenuId': '4302338945',
                  'appMenuCode': '436638',
                  'appMenuRelativeUri': 'mdm/#/businessUnit',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '业务单元',
                  'appMenuList': []
                }, {
                  'appMenuId': '82010555730122752',
                  'appMenuCode': '399000003',
                  'appMenuRelativeUri': 'mdm/#/consulting',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '诊疗组',
                  'appMenuList': []
                }, {
                  'appMenuId': '4302295385',
                  'appMenuCode': '436606',
                  'appMenuRelativeUri': 'mdm/#/businessUnitRelation',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '临床护理业务单元',
                  'appMenuList': []
                }, {
                  'appMenuId': '4300203755',
                  'appMenuCode': '347717',
                  'appMenuRelativeUri': 'webui-admin-material/#/RecordAllocation/StoreRoom',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '库房',
                  'appMenuList': []
                }, {
                  'appMenuId': '108388063118585856',
                  'appMenuCode': '399207425',
                  'appMenuRelativeUri': 'mdm/#/recordAllocation/supplier',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '供应商',
                  'appMenuList': []
                }
              ]
            }, {
              'appMenuId': '4300000035',
              'appMenuCode': '256031',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '资源',
              'appMenuList': [
                {
                  'appMenuId': '4300000037',
                  'appMenuCode': '256033',
                  'appMenuRelativeUri': 'mdm/#/person',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '员工',
                  'appMenuList': []
                }, {
                  'appMenuId': '4302295386',
                  'appMenuCode': '436607',
                  'appMenuRelativeUri': 'mdm/#/time',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '时间',
                  'appMenuList': []
                }, {
                  'appMenuId': '4302295387',
                  'appMenuCode': '436608',
                  'appMenuRelativeUri': 'mdm/#/site',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '位置',
                  'appMenuList': []
                }, {
                  'appMenuId': '4300150102',
                  'appMenuCode': '256763',
                  'appMenuRelativeUri': 'webui-admin-material/#/RecordAllocation/DrugGenericName',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '药品通用名',
                  'appMenuList': []
                }, {
                  'appMenuId': '4300150103',
                  'appMenuCode': '256764',
                  'appMenuRelativeUri': 'webui-admin-material/#/RecordAllocation/DrugProduct',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '药品',
                  'appMenuList': []
                }, {
                  'appMenuId': '4302737195',
                  'appMenuCode': '873054',
                  'appMenuRelativeUri': 'webui-admin-material/#/RecordAllocation/ProductGenericNameRelation',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '药品与通用名对照',
                  'appMenuList': []
                }
              ]
            }, {
              'appMenuId': '4300000022',
              'appMenuCode': '256018',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '服务',
              'appMenuList': [
                {
                  'appMenuId': '4300000023',
                  'appMenuCode': '256019',
                  'appMenuRelativeUri': 'webui-admin-clinical/#/ClinicalServe',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '临床服务',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303246920',
                  'appMenuCode': '376485',
                  'appMenuRelativeUri': 'webui-admin-encounter/#/patientConsultation/subjectSetting',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '科目设置',
                  'appMenuList': []
                }, {
                  'appMenuId': '4300000024',
                  'appMenuCode': '256020',
                  'appMenuRelativeUri': 'mdm/#/business',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '业务活动',
                  'appMenuList': []
                }
              ]
            }, {
              'appMenuId': '4300000040',
              'appMenuCode': '256036',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '权限配置',
              'appMenuList': [
                {
                  'appMenuId': '4300000042',
                  'appMenuCode': '256038',
                  'appMenuRelativeUri': 'mdm/#/role',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '角色',
                  'appMenuList': []
                }
              ]
            }, {
              'appMenuId': '4300000039',
              'appMenuCode': '256035',
              'appMenuRelativeUri': 'mdm/#/queryconfig',
              'appMenuTypeCode': '256053',
              'appMenuName': '参数配置',
              'appMenuList': []
            }, {
              'appMenuId': '4300200120',
              'appMenuCode': '256932',
              'appMenuRelativeUri': 'mdm/#/codeRule',
              'appMenuTypeCode': '256053',
              'appMenuName': '编码规则',
              'appMenuList': []
            }, {
              'appMenuId': '4300000020',
              'appMenuCode': '256016',
              'appMenuRelativeUri': 'mdm/#/term',
              'appMenuTypeCode': '256053',
              'appMenuName': '术语',
              'appMenuList': []
            }, {
              'appMenuId': '4303919474',
              'appMenuCode': '991647',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '映射',
              'appMenuList': [
                {
                  'appMenuId': '4302708392',
                  'appMenuCode': '870058',
                  'appMenuRelativeUri': 'mdm/#/termMapping',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '术语映射',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303919478',
                  'appMenuCode': '991648',
                  'appMenuRelativeUri': 'webui-admin-mdm/#/inspectionHIS',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '检验映射',
                  'appMenuList': []
                }, {
                  'appMenuId': '92228968066070528',
                  'appMenuCode': '399011068',
                  'appMenuRelativeUri': 'mdm/#/checkMapping',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '检查映射',
                  'appMenuList': []
                }
              ]
            }
          ]
        }, {
          'appMenuId': '4300000044',
          'appMenuCode': '256040',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '患者域',
          'appMenuList': [
            {
              'appMenuId': '4300239102',
              'appMenuCode': '376697',
              'appMenuRelativeUri': 'webui-admin-person/#/patientConsultation/ageGroup',
              'appMenuTypeCode': '256053',
              'appMenuName': '年龄段设置',
              'appMenuList': []
            }, {
              'appMenuId': '4300239103',
              'appMenuCode': '376698',
              'appMenuRelativeUri': 'webui-admin-person/#/patientConsultation/ageSetting',
              'appMenuTypeCode': '256053',
              'appMenuName': '年龄显示设置',
              'appMenuList': []
            }, {
              'appMenuId': '4300239761',
              'appMenuCode': '376892',
              'appMenuRelativeUri': 'webui-admin-person/#/patientConsultation/interfaceReader',
              'appMenuTypeCode': '256053',
              'appMenuName': '读卡组件设置',
              'appMenuList': []
            }, {
              'appMenuId': '4302689343',
              'appMenuCode': '869467',
              'appMenuRelativeUri': 'webui-admin-person/#/patientConsultation/ageGroupInterval',
              'appMenuTypeCode': '256053',
              'appMenuName': '年龄段区间设置',
              'appMenuList': []
            }, {
              'appMenuId': '4303002427',
              'appMenuCode': '951935',
              'appMenuRelativeUri': 'webui-admin-person/#/patientConsultation/personMPI',
              'appMenuTypeCode': '256053',
              'appMenuName': '患者MPI规则',
              'appMenuList': []
            }, {
              'appMenuId': '4303064956',
              'appMenuCode': '952434',
              'appMenuRelativeUri': 'webui-admin-person/#/patientRecord/recordSet',
              'appMenuTypeCode': '256053',
              'appMenuName': '患者建档数据配置',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '4300000045',
          'appMenuCode': '256041',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '就诊域',
          'appMenuList': [
            {
              'appMenuId': '4300231806',
              'appMenuCode': '376485',
              'appMenuRelativeUri': 'webui-admin-encounter/#/patientConsultation/subjectSetting',
              'appMenuTypeCode': '256053',
              'appMenuName': '科目设置',
              'appMenuList': []
            }, {
              'appMenuId': '4300235373',
              'appMenuCode': '376684',
              'appMenuRelativeUri': 'webui-admin-encounter/#/patientConsultation/departmentSetting',
              'appMenuTypeCode': '256053',
              'appMenuName': 'banner显示设置',
              'appMenuList': []
            }, {
              'appMenuId': '4300239762',
              'appMenuCode': '376893',
              'appMenuRelativeUri': 'webui-admin-encounter/#/patientConsultation/departmentClassify',
              'appMenuTypeCode': '256053',
              'appMenuName': '科室分类设置',
              'appMenuList': []
            }, {
              'appMenuId': '4302437998',
              'appMenuCode': '862181',
              'appMenuRelativeUri': 'webui-admin-encounter/#/scheduleSystem/operater',
              'appMenuTypeCode': '256053',
              'appMenuName': '排班人员权限管理',
              'appMenuList': []
            }, {
              'appMenuId': '4302437999',
              'appMenuCode': '862182',
              'appMenuRelativeUri': 'webui-admin-encounter/#/scheduleSystem/channel',
              'appMenuTypeCode': '256053',
              'appMenuName': '渠道管理',
              'appMenuList': []
            }, {
              'appMenuId': '4302438000',
              'appMenuCode': '862183',
              'appMenuRelativeUri': 'webui-admin-encounter/#/scheduleSystem/schedulePool',
              'appMenuTypeCode': '256053',
              'appMenuName': '号池设置',
              'appMenuList': []
            }, {
              'appMenuId': '4302903656',
              'appMenuCode': '950255',
              'appMenuRelativeUri': 'webui-admin-encounter/#/patientConsultation/clinicArea',
              'appMenuTypeCode': '256053',
              'appMenuName': '诊区、诊间、诊台',
              'appMenuList': []
            }, {
              'appMenuId': '4302979582',
              'appMenuCode': '951913',
              'appMenuRelativeUri': 'webui-admin-encounter/#/scheduleSystem/defaultConfig',
              'appMenuTypeCode': '256053',
              'appMenuName': '初始化默认设置',
              'appMenuList': []
            }, {
              'appMenuId': '4303005986',
              'appMenuCode': '952138',
              'appMenuRelativeUri': 'webui-admin-encounter/#/patientConsultation/feeSetting',
              'appMenuTypeCode': '256053',
              'appMenuName': '就诊收费服务设置',
              'appMenuList': []
            }, {
              'appMenuId': '4303434195',
              'appMenuCode': '959855',
              'appMenuRelativeUri': 'webui-admin-encounter/#/scheduleSystem/registerRules',
              'appMenuTypeCode': '256053',
              'appMenuName': '就诊规则管理',
              'appMenuList': []
            }, {
              'appMenuId': '4303603067',
              'appMenuCode': '959956',
              'appMenuRelativeUri': 'webui-admin-encounter/#/patientConsultation/sickbedSetting',
              'appMenuTypeCode': '256053',
              'appMenuName': '病房与床位设置',
              'appMenuList': []
            }, {
              'appMenuId': '4303603071',
              'appMenuCode': '959957',
              'appMenuRelativeUri': 'webui-admin-encounter/#/patientConsultation/bedcardSetting',
              'appMenuTypeCode': '256053',
              'appMenuName': '床位卡内容设置',
              'appMenuList': []
            }, {
              'appMenuId': '88853959136192513',
              'appMenuCode': '399001352',
              'appMenuRelativeUri': 'webui-admin-encounter/#/patientConsultation/bedCardScreen',
              'appMenuTypeCode': '256053',
              'appMenuName': '床位卡筛选分组',
              'appMenuList': []
            }, {
              'appMenuId': '96469030641262593',
              'appMenuCode': '399015385',
              'appMenuRelativeUri': 'webui-admin-encounter/#/patientConsultation/preServiceSetting',
              'appMenuTypeCode': '256053',
              'appMenuName': '院前服务配置',
              'appMenuList': []
            }, {
              'appMenuId': '97587111516291073',
              'appMenuCode': '399016404',
              'appMenuRelativeUri': 'webui-admin-encounter/#/outpatientSetting/outpatientSetting',
              'appMenuTypeCode': '256053',
              'appMenuName': '门诊就诊列表设置',
              'appMenuList': []
            }, {
              'appMenuId': '101852746360625153',
              'appMenuCode': '399184809',
              'appMenuRelativeUri': 'webui-admin-encounter/#/outpatientSetting/certificateSetting',
              'appMenuTypeCode': '256053',
              'appMenuName': '门诊单据设置',
              'appMenuList': []
            }, {
              'appMenuId': '108348055498223617',
              'appMenuCode': '399207288',
              'appMenuRelativeUri': 'webui-admin-encounter/#/triageSetting/triageSetting',
              'appMenuTypeCode': '256053',
              'appMenuName': '分诊规则设置',
              'appMenuList': []
            }, {
              'appMenuId': '108348094152929281',
              'appMenuCode': '399207298',
              'appMenuRelativeUri': 'webui-admin-encounter/#/triageSetting/deviceBindingSetting',
              'appMenuTypeCode': '256053',
              'appMenuName': '分诊设备绑定设置',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '4300000046',
          'appMenuCode': '256042',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '临床域',
          'appMenuList': [
            {
              'appMenuId': '4300235211',
              'appMenuCode': '376538',
              'appMenuRelativeUri': 'webui-admin-clinical/#/ClinicalServe',
              'appMenuTypeCode': '256053',
              'appMenuName': '临床服务设置',
              'appMenuList': []
            }, {
              'appMenuId': '4300235212',
              'appMenuCode': '376539',
              'appMenuRelativeUri': 'webui-admin-clinical/#/ClinicalClassify',
              'appMenuTypeCode': '256053',
              'appMenuName': '临床服务分类设置',
              'appMenuList': []
            }, {
              'appMenuId': '4300235213',
              'appMenuCode': '376540',
              'appMenuRelativeUri': 'webui-admin-clinical/#/DoctorsRights',
              'appMenuTypeCode': '256053',
              'appMenuName': '医生权限配置',
              'appMenuList': []
            }, {
              'appMenuId': '4300235215',
              'appMenuCode': '376542',
              'appMenuRelativeUri': 'webui-admin-clinical/#/AdviceCheckRules/AdvicecheckRulesList',
              'appMenuTypeCode': '256053',
              'appMenuName': '医嘱规则',
              'appMenuList': []
            }, {
              'appMenuId': '4300235216',
              'appMenuCode': '376543',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '联动规则',
              'appMenuList': [
                {
                  'appMenuId': '4300235218',
                  'appMenuCode': '376550',
                  'appMenuRelativeUri': 'webui-admin-clinical/#/LinkageRules/dosageRules',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '给药途径',
                  'appMenuList': []
                }, {
                  'appMenuId': '4300235220',
                  'appMenuCode': '376545',
                  'appMenuRelativeUri': 'webui-admin-clinical/#/LinkageRules/herbalRules',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '中医联动',
                  'appMenuList': []
                }, {
                  'appMenuId': '4300235222',
                  'appMenuCode': '376548',
                  'appMenuRelativeUri': 'webui-admin-clinical/#/LinkageRules/photographySet',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '造影剂设置',
                  'appMenuList': []
                }, {
                  'appMenuId': '4300235223',
                  'appMenuCode': '376549',
                  'appMenuRelativeUri': 'webui-admin-clinical/#/LinkageRules/mediumSet',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '媒介项目设置',
                  'appMenuList': []
                }
              ]
            }, {
              'appMenuId': '4302406442',
              'appMenuCode': '862148',
              'appMenuRelativeUri': 'webui-admin-clinical/#/adviceTemplate',
              'appMenuTypeCode': '256053',
              'appMenuName': '医嘱模板设置',
              'appMenuList': []
            }, {
              'appMenuId': '4302708397',
              'appMenuCode': '870059',
              'appMenuRelativeUri': 'webui-admin-clinical/#/CheckItemClassify',
              'appMenuTypeCode': '256053',
              'appMenuName': '检查项目分类',
              'appMenuList': []
            }, {
              'appMenuId': '4303657212',
              'appMenuCode': '960348',
              'appMenuRelativeUri': 'webui-admin-clinical/#/DosageRouteSet',
              'appMenuTypeCode': '256053',
              'appMenuName': '给药途径设置',
              'appMenuList': []
            }, {
              'appMenuId': '4303657216',
              'appMenuCode': '960349',
              'appMenuRelativeUri': 'webui-admin-clinical/#/FrequencySet',
              'appMenuTypeCode': '256053',
              'appMenuName': '频次属性设置',
              'appMenuList': []
            }, {
              'appMenuId': '4303919389',
              'appMenuCode': '991308',
              'appMenuRelativeUri': 'webui-admin-clinical/#/AdviceDisplaySetting/inpatient',
              'appMenuTypeCode': '256053',
              'appMenuName': '医嘱显示设置',
              'appMenuList': []
            }, {
              'appMenuId': '99096846235408384',
              'appMenuCode': '399018651',
              'appMenuRelativeUri': 'webui-admin-clinical/#/PrescSearchConfig',
              'appMenuTypeCode': '256053',
              'appMenuName': '检索配置设置',
              'appMenuList': []
            }, {
              'appMenuId': '101870042193926145',
              'appMenuCode': '399184836',
              'appMenuRelativeUri': 'webui-admin-clinical/#/RequisitionTemplate',
              'appMenuTypeCode': '256053',
              'appMenuName': '检验申请单',
              'appMenuList': []
            }, {
              'appMenuId': '103179998629271552',
              'appMenuCode': '399200466',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '抗菌药物使用规则',
              'appMenuList': [
                {
                  'appMenuId': '103180054463846400',
                  'appMenuCode': '399200467',
                  'appMenuRelativeUri': 'webui-admin-clinical/#/AntiMedicineRule/AntiApplicableRule',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '应用场景',
                  'appMenuList': []
                }, {
                  'appMenuId': '103180108150937600',
                  'appMenuCode': '399200468',
                  'appMenuRelativeUri': 'webui-admin-clinical/#/AntiMedicineRule/AntiDocMedRule',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '使用权限',
                  'appMenuList': []
                }
              ]
            }, {
              'appMenuId': '106506362784280577',
              'appMenuCode': '399203100',
              'appMenuRelativeUri': 'webui-admin-clinical/#/ACForm/CheckUp',
              'appMenuTypeCode': '256053',
              'appMenuName': '检查申请单',
              'appMenuList': []
            }, {
              'appMenuId': '108963958103437312',
              'appMenuCode': '399207841',
              'appMenuRelativeUri': 'webui-admin-clinical/#/ACForm/Treat',
              'appMenuTypeCode': '256053',
              'appMenuName': '治疗申请单',
              'appMenuList': []
            }, {
              'appMenuId': '109111393593290752',
              'appMenuCode': '399207987',
              'appMenuRelativeUri': 'webui-admin-clinical/#/ClinicalSetting',
              'appMenuTypeCode': '256053',
              'appMenuName': '临床配置',
              'appMenuList': []
            }, {
              'appMenuId': '110251441122406401',
              'appMenuCode': '399208991',
              'appMenuRelativeUri': 'webui-admin-clinical/#/DrugDeliveryRouteQuery',
              'appMenuTypeCode': '256053',
              'appMenuName': '给药途径查询',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '4300000047',
          'appMenuCode': '256043',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '执行域',
          'appMenuList': [
            {
              'appMenuId': '4300235214',
              'appMenuCode': '376541',
              'appMenuRelativeUri': 'webui-admin-execution/#/DoctorAdviceDirection',
              'appMenuTypeCode': '256053',
              'appMenuName': '医嘱流向配置 ',
              'appMenuList': []
            }, {
              'appMenuId': '4302942786',
              'appMenuCode': '951766',
              'appMenuRelativeUri': 'webui-admin-execution/#/config/list',
              'appMenuTypeCode': '256053',
              'appMenuName': '医技报告类别配置',
              'appMenuList': []
            }, {
              'appMenuId': '92597946558986240',
              'appMenuCode': '399011456',
              'appMenuRelativeUri': 'webui-admin-execution/#/ServiceLinkage',
              'appMenuTypeCode': '256053',
              'appMenuName': '医嘱联动配置',
              'appMenuList': []
            }, {
              'appMenuId': '102447968698308608',
              'appMenuCode': '399185050',
              'appMenuRelativeUri': 'webui-admin-execution/#/PerformClassification',
              'appMenuTypeCode': '256053',
              'appMenuName': '医嘱执行分类',
              'appMenuList': []
            }, {
              'appMenuId': '102448037417785345',
              'appMenuCode': '399185051',
              'appMenuRelativeUri': 'webui-admin-execution/#/ExecutionRuleConditions',
              'appMenuTypeCode': '256053',
              'appMenuName': '执行规则条件',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '4300000048',
          'appMenuCode': '256044',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '费用域',
          'appMenuList': [
            {
              'appMenuId': '4300200133',
              'appMenuCode': '263886',
              'appMenuRelativeUri': 'webui-admin-finance/strategySet.html',
              'appMenuTypeCode': '256053',
              'appMenuName': '计费策略类设置',
              'appMenuList': []
            }, {
              'appMenuId': '4300200134',
              'appMenuCode': '263887',
              'appMenuRelativeUri': 'webui-admin-finance/serveBillingSet.html',
              'appMenuTypeCode': '256053',
              'appMenuName': '服务计费策略设置',
              'appMenuList': []
            }, {
              'appMenuId': '4300203756',
              'appMenuCode': '347822',
              'appMenuRelativeUri': 'webui-admin-finance/billingSet.html',
              'appMenuTypeCode': '256053',
              'appMenuName': '计费大项目',
              'appMenuList': []
            }, {
              'appMenuId': '4300203757',
              'appMenuCode': '347823',
              'appMenuRelativeUri': 'webui-admin-finance/chargeSet.html',
              'appMenuTypeCode': '256053',
              'appMenuName': '收费大项目',
              'appMenuList': []
            }, {
              'appMenuId': '4300203758',
              'appMenuCode': '347824',
              'appMenuRelativeUri': 'webui-admin-finance/medicalInsurance.html',
              'appMenuTypeCode': '256053',
              'appMenuName': '医疗保险',
              'appMenuList': []
            }, {
              'appMenuId': '4300203759',
              'appMenuCode': '347825',
              'appMenuRelativeUri': 'webui-admin-finance/chargeItemSet.html',
              'appMenuTypeCode': '256053',
              'appMenuName': '收费项目',
              'appMenuList': []
            }, {
              'appMenuId': '4302706256',
              'appMenuCode': '869488',
              'appMenuRelativeUri': 'fee-management-outp',
              'appMenuTypeCode': '256053',
              'appMenuName': '门诊费用管理',
              'appMenuList': []
            }, {
              'appMenuId': '4303086489',
              'appMenuCode': '955903',
              'appMenuRelativeUri': 'webui-admin-finance/errMsgSetting.html',
              'appMenuTypeCode': '256053',
              'appMenuName': '智慧提示',
              'appMenuList': []
            }, {
              'appMenuId': '4303155802',
              'appMenuCode': '958108',
              'appMenuRelativeUri': 'webui-admin-finance/invoicePrintRuleSet.html',
              'appMenuTypeCode': '256053',
              'appMenuName': '票据打印规则',
              'appMenuList': []
            }, {
              'appMenuId': '4303246936',
              'appMenuCode': '959604',
              'appMenuRelativeUri': 'webui-admin-finance/payManagement.html',
              'appMenuTypeCode': '256053',
              'appMenuName': '支付方式管理',
              'appMenuList': []
            }, {
              'appMenuId': '4303246944',
              'appMenuCode': '959606',
              'appMenuRelativeUri': 'webui-admin-finance/clientApiLibExtSet.html',
              'appMenuTypeCode': '256053',
              'appMenuName': '接口管理',
              'appMenuList': []
            }, {
              'appMenuId': '4303246948',
              'appMenuCode': '959607',
              'appMenuRelativeUri': 'webui-admin-finance/payWindowMgt.html',
              'appMenuTypeCode': '256053',
              'appMenuName': '收费窗口管理',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '4300000049',
          'appMenuCode': '256045',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '协同域',
          'appMenuList': [
            {
              'appMenuId': '4302708190',
              'appMenuCode': '869492',
              'appMenuRelativeUri': 'webui-admin-cooperation/#/consumerSetting',
              'appMenuTypeCode': '256053',
              'appMenuName': '消费方设置',
              'appMenuList': []
            }, {
              'appMenuId': '4302708191',
              'appMenuCode': '869493',
              'appMenuRelativeUri': 'webui-admin-cooperation/#/printerManagement',
              'appMenuTypeCode': '256053',
              'appMenuName': '打印机管理',
              'appMenuList': []
            }, {
              'appMenuId': '4302708192',
              'appMenuCode': '869494',
              'appMenuRelativeUri': 'webui-admin-cooperation/#/templateManagement',
              'appMenuTypeCode': '256053',
              'appMenuName': '模板管理',
              'appMenuList': []
            }, {
              'appMenuId': '4303070610',
              'appMenuCode': '954088',
              'appMenuRelativeUri': 'webui-admin-cooperation/#/softwareServiceManagement',
              'appMenuTypeCode': '256053',
              'appMenuName': '软件服务管理',
              'appMenuList': []
            }, {
              'appMenuId': '4303070614',
              'appMenuCode': '954089',
              'appMenuRelativeUri': 'webui-admin-cooperation/#/serviceSubscriptionManagement',
              'appMenuTypeCode': '256053',
              'appMenuName': '服务订用管理 ',
              'appMenuList': []
            }, {
              'appMenuId': '105374432692316161',
              'appMenuCode': '399202373',
              'appMenuRelativeUri': 'webui-admin-cooperation/#/registeredManagement',
              'appMenuTypeCode': '256053',
              'appMenuName': '组件注册',
              'appMenuList': []
            }, {
              'appMenuId': '105374512149211136',
              'appMenuCode': '399202374',
              'appMenuRelativeUri': 'webui-admin-cooperation/#/authorizeManagement',
              'appMenuTypeCode': '256053',
              'appMenuName': '组件授权',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '4300000050',
          'appMenuCode': '256046',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '物品域',
          'appMenuList': [
            {
              'appMenuId': '4303246924',
              'appMenuCode': '256763',
              'appMenuRelativeUri': 'webui-admin-material/#/RecordAllocation/DrugGenericName',
              'appMenuTypeCode': '256053',
              'appMenuName': '药品通用名',
              'appMenuList': []
            }, {
              'appMenuId': '4303246928',
              'appMenuCode': '256764',
              'appMenuRelativeUri': 'webui-admin-material/#/RecordAllocation/DrugProduct',
              'appMenuTypeCode': '256053',
              'appMenuName': '药品',
              'appMenuList': []
            }, {
              'appMenuId': '4303246932',
              'appMenuCode': '873054',
              'appMenuRelativeUri': 'webui-admin-material/#/RecordAllocation/ProductGenericNameRelation',
              'appMenuTypeCode': '256053',
              'appMenuName': '药品与通用名对照',
              'appMenuList': []
            }, {
              'appMenuId': '4300231804',
              'appMenuCode': '376410',
              'appMenuRelativeUri': 'webui-admin-material/#/RecordAllocation/Formulation',
              'appMenuTypeCode': '256053',
              'appMenuName': '剂型与给药途径',
              'appMenuList': []
            }, {
              'appMenuId': '4302259106',
              'appMenuCode': '436584',
              'appMenuRelativeUri': 'webui-admin-material/#/RecordAllocation/DrugAllergyRule',
              'appMenuTypeCode': '256053',
              'appMenuName': '药品过敏规则',
              'appMenuList': []
            }, {
              'appMenuId': '4302259107',
              'appMenuCode': '436585',
              'appMenuRelativeUri': 'webui-admin-material/#/RecordAllocation/DrugUsageRule',
              'appMenuTypeCode': '256053',
              'appMenuName': '药品用量规则',
              'appMenuList': []
            }, {
              'appMenuId': '4303837482',
              'appMenuCode': '977597',
              'appMenuRelativeUri': 'webui-admin-material/#/RecordAllocation/SkinTestGenericNameRelation',
              'appMenuTypeCode': '256053',
              'appMenuName': '皮试服务对照',
              'appMenuList': []
            }, {
              'appMenuId': '4303872055',
              'appMenuCode': '980165',
              'appMenuRelativeUri': 'webui-admin-material/#/RecordAllocation/DrugRoomCatalog',
              'appMenuTypeCode': '256053',
              'appMenuName': '药房商品目录',
              'appMenuList': []
            }, {
              'appMenuId': '4303919499',
              'appMenuCode': '1000046',
              'appMenuRelativeUri': 'webui-admin-material/#/RecordAllocation/DrugOrderSetting',
              'appMenuTypeCode': '256053',
              'appMenuName': '领药单据设置',
              'appMenuList': []
            }, {
              'appMenuId': '93728478557794304',
              'appMenuCode': '399014757',
              'appMenuRelativeUri': '/webui-admin-material/#/Supplies/SuppliesCatalog',
              'appMenuTypeCode': '256053',
              'appMenuName': '物资分类',
              'appMenuList': []
            }, {
              'appMenuId': '93728519359983617',
              'appMenuCode': '399014758',
              'appMenuRelativeUri': '/webui-admin-material/#/Supplies/SuppliesProduct',
              'appMenuTypeCode': '256053',
              'appMenuName': '物资商品',
              'appMenuList': []
            }, {
              'appMenuId': '93728558014689280',
              'appMenuCode': '399014759',
              'appMenuRelativeUri': '/webui-admin-material/#/Supplies/SuppliesService',
              'appMenuTypeCode': '256053',
              'appMenuName': '物资服务',
              'appMenuList': []
            }, {
              'appMenuId': '106671637420797953',
              'appMenuCode': '399203509',
              'appMenuRelativeUri': '/webui-admin-material/#/Supplies/Combination',
              'appMenuTypeCode': '256053',
              'appMenuName': '物资组合包',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '4300000051',
          'appMenuCode': '256047',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '记录域',
          'appMenuList': [
            {
              'appMenuId': '4300203751',
              'appMenuCode': '347636',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '定义态',
              'appMenuList': [
                {
                  'appMenuId': '4300200119',
                  'appMenuCode': '256933',
                  'appMenuRelativeUri': 'webui-admin-emr/#/RecordAllocation/MedicalRecord',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '临床文档',
                  'appMenuList': []
                }, {
                  'appMenuId': '4300200118',
                  'appMenuCode': '256934',
                  'appMenuRelativeUri': 'webui-admin-emr/#/RecordAllocation/ClinicalSection',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '临床段落',
                  'appMenuList': []
                }, {
                  'appMenuId': '4300203750',
                  'appMenuCode': '347637',
                  'appMenuRelativeUri': 'webui-admin-emr/#/RecordAllocation/clinicalOntology',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '临床片段',
                  'appMenuList': []
                }, {
                  'appMenuId': '4300200117',
                  'appMenuCode': '256935',
                  'appMenuRelativeUri': 'webui-admin-emr/#/RecordAllocation/ClinicalEntry',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '临床单元',
                  'appMenuList': []
                }
              ]
            }, {
              'appMenuId': '4300203752',
              'appMenuCode': '347638',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '知识态',
              'appMenuList': [
                {
                  'appMenuId': '4300203753',
                  'appMenuCode': '347639',
                  'appMenuRelativeUri': 'webui-admin-emr/#/medicalRecordList',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '病历知识文档',
                  'appMenuList': []
                }, {
                  'appMenuId': '109094834346881025',
                  'appMenuCode': '399207962',
                  'appMenuRelativeUri': 'webui-admin-emr/#/medicalRecordList?type=1',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '医生个人模板',
                  'appMenuList': []
                }, {
                  'appMenuId': '91148901902727169',
                  'appMenuCode': '399010091',
                  'appMenuRelativeUri': 'webui-admin-emr/#/richtextConfig',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '现病史',
                  'appMenuList': []
                }, {
                  'appMenuId': '4302244538',
                  'appMenuCode': '436576',
                  'appMenuRelativeUri': 'webui-admin-emr/#/recordHistoryBookList',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '病历簿配置管理',
                  'appMenuList': []
                }, {
                  'appMenuId': '4302283477',
                  'appMenuCode': '436602',
                  'appMenuRelativeUri': 'webui-admin-emr/#/templateRelease',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '知识文档发布管理',
                  'appMenuList': []
                }
              ]
            }, {
              'appMenuId': '4302438004',
              'appMenuCode': '862184',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '诊断配置',
              'appMenuList': [
                {
                  'appMenuId': '4302438005',
                  'appMenuCode': '862185',
                  'appMenuRelativeUri': 'webui-admin-diagnosis/#/SpecialCategoryExtendAttrSetting',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '专科类别扩展属性',
                  'appMenuList': []
                }, {
                  'appMenuId': '4302438006',
                  'appMenuCode': '862186',
                  'appMenuRelativeUri': 'webui-admin-diagnosis/#/SpecialCategoryDiagnosisSetting',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '专科类别诊断对应',
                  'appMenuList': []
                }, {
                  'appMenuId': '4302438007',
                  'appMenuCode': '862187',
                  'appMenuRelativeUri': 'webui-admin-diagnosis/#/DiagnosisSystemMaintain',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '医院诊断体系维护',
                  'appMenuList': []
                }, {
                  'appMenuId': '4302438008',
                  'appMenuCode': '862188',
                  'appMenuRelativeUri': 'webui-admin-diagnosis/#/HospitalDiagnosisMaintain',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '院内诊断维护',
                  'appMenuList': []
                }, {
                  'appMenuId': '4302438009',
                  'appMenuCode': '862189',
                  'appMenuRelativeUri': 'webui-admin-diagnosis/#/DiagnosisScopeLimit',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '诊断范围限定',
                  'appMenuList': []
                }, {
                  'appMenuId': '4302438010',
                  'appMenuCode': '862190',
                  'appMenuRelativeUri': 'webui-admin-diagnosis/#/DiagnosisCoreespondingSetting',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '诊断对应设置',
                  'appMenuList': []
                }, {
                  'appMenuId': '4302438011',
                  'appMenuCode': '862191',
                  'appMenuRelativeUri': 'webui-admin-diagnosis/#/GeneralDiagnosisMaintain',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '常用诊断维护',
                  'appMenuList': []
                }
              ]
            }
          ]
        }, {
          'appMenuId': '4300000052',
          'appMenuCode': '256048',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '知识域',
          'appMenuList': [
            {
              'appMenuId': '110230127347200000',
              'appMenuCode': '399208986',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '医学知识推荐',
              'appMenuList': [
                {
                  'appMenuId': '4302401549',
                  'appMenuCode': '604850',
                  'appMenuRelativeUri': 'webui-admin-knowledge/#/knowledgeRecommendation/serviceConfig',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '知识与临床服务',
                  'appMenuList': []
                }, {
                  'appMenuId': '89414357811249152',
                  'appMenuCode': '399001638',
                  'appMenuRelativeUri': 'webui-admin-knowledge/#/knowledgeRecommendation/clinicalSubjectConfig',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '常见症状与病种',
                  'appMenuList': []
                }, {
                  'appMenuId': '111522820161499136',
                  'appMenuCode': '399210566',
                  'appMenuRelativeUri': 'webui-admin-knowledge/#/knowledgeRecommendation/chartBaseConfig',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '图数据库管理',
                  'appMenuList': []
                }
              ]
            }, {
              'appMenuId': '110230249753767936',
              'appMenuCode': '399208987',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '诊疗路径推荐',
              'appMenuList': [
                {
                  'appMenuId': '89984731687467009',
                  'appMenuCode': '399010037',
                  'appMenuRelativeUri': 'webui-admin-knowledge/#/treatmentPathRecommendation/clinicalPath',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '诊疗路径',
                  'appMenuList': []
                }, {
                  'appMenuId': '91650706554238976',
                  'appMenuCode': '399010962',
                  'appMenuRelativeUri': 'webui-admin-knowledge/#/treatmentPathRecommendation/symptomAndDiagnosis',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '个人症状与诊断',
                  'appMenuList': []
                }
              ]
            }, {
              'appMenuId': '110230288408473601',
              'appMenuCode': '399208988',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '知识域配置',
              'appMenuList': [
                {
                  'appMenuId': '97621791229722624',
                  'appMenuCode': '399016426',
                  'appMenuRelativeUri': 'webui-admin-knowledge/#/knowledgeConfig/externalKnowledgeBaseConfig',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '外部知识库配置',
                  'appMenuList': []
                }, {
                  'appMenuId': '108384854778015744',
                  'appMenuCode': '399207424',
                  'appMenuRelativeUri': 'webui-admin-knowledge/#/knowledgeConfig/parameterConfig',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '个性化配置  ',
                  'appMenuList': []
                }
              ]
            }
          ]
        }
      ]
    }, {
      'appSystemId': '4303212347',
      'appSystemName': '病案系统',
      'appSystemPicUrl': 'c:\\',
      'appSystemRelativeUri': 'web-medical-archive-portal/index/#/toDoList',
      'appMenuList': [
        {
          'appMenuId': '4303724405',
          'appMenuCode': '958599',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/qcRanking/scoreRanking',
          'appMenuTypeCode': '256053',
          'appMenuName': '评分排名',
          'appMenuList': []
        }, {
          'appMenuId': '4303724409',
          'appMenuCode': '958600',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/qcRanking/problemRanking',
          'appMenuTypeCode': '256053',
          'appMenuName': '问题排名',
          'appMenuList': []
        }, {
          'appMenuId': '4303724413',
          'appMenuCode': '958601',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/qcRanking/reworkRanking',
          'appMenuTypeCode': '256053',
          'appMenuName': '返修排名',
          'appMenuList': []
        }, {
          'appMenuId': '4303724313',
          'appMenuCode': '958590',
          'appMenuRelativeUri': 'web-medical-archive-portal/#/toDoList',
          'appMenuTypeCode': '256053',
          'appMenuName': '病案主页',
          'appMenuList': []
        }, {
          'appMenuId': '4303724317',
          'appMenuCode': '960810',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/drhomeManagement',
          'appMenuTypeCode': '256053',
          'appMenuName': '首页编码',
          'appMenuList': [
            {
              'appMenuId': '82408978464653313',
              'appMenuCode': '399000017',
              'appMenuRelativeUri': 'web-medical-archive-qc/#/drhomeManagement/drhomepagecode',
              'appMenuTypeCode': '872106',
              'appMenuName': '待编码',
              'appMenuList': []
            }, {
              'appMenuId': '82409032151744512',
              'appMenuCode': '399000018',
              'appMenuRelativeUri': 'web-medical-archive-qc/#/drhomeManagement/drencoded',
              'appMenuTypeCode': '872106',
              'appMenuName': '已编码',
              'appMenuList': []
            }, {
              'appMenuId': '82409079396384769',
              'appMenuCode': '399000019',
              'appMenuRelativeUri': 'web-medical-archive-qc/#/drhomeManagement/drunsubmitted',
              'appMenuTypeCode': '872106',
              'appMenuName': '医生未提交',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '4303724321',
          'appMenuCode': '960811',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/homeManagement',
          'appMenuTypeCode': '256053',
          'appMenuName': '首页录入',
          'appMenuList': [
            {
              'appMenuId': '82409137378443264',
              'appMenuCode': '399000020',
              'appMenuRelativeUri': 'web-medical-archive-qc/#/homeManagement/homepagecode',
              'appMenuTypeCode': '872106',
              'appMenuName': '待录入',
              'appMenuList': []
            }, {
              'appMenuId': '82409173885665280',
              'appMenuCode': '399000021',
              'appMenuRelativeUri': 'web-medical-archive-qc/#/homeManagement/enrcorded',
              'appMenuTypeCode': '872106',
              'appMenuName': '已录入',
              'appMenuList': []
            }, {
              'appMenuId': '82409210392887297',
              'appMenuCode': '399000022',
              'appMenuRelativeUri': 'web-medical-archive-qc/#/homeManagement/uncoded',
              'appMenuTypeCode': '872106',
              'appMenuName': '未编码',
              'appMenuList': []
            }, {
              'appMenuId': '82409266227462144',
              'appMenuCode': '399000023',
              'appMenuRelativeUri': 'web-medical-archive-qc/#/homeManagement/unfinished',
              'appMenuTypeCode': '872106',
              'appMenuName': '未质控',
              'appMenuList': []
            }, {
              'appMenuId': '82409354274291713',
              'appMenuCode': '399000024',
              'appMenuRelativeUri': 'web-medical-archive-qc/#/homeManagement/unsubmitted',
              'appMenuTypeCode': '872106',
              'appMenuName': '医生未提交',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '4303724325',
          'appMenuCode': '960812',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/basicQueryByKeyword',
          'appMenuTypeCode': '256053',
          'appMenuName': '首页关键字查询',
          'appMenuList': []
        }, {
          'appMenuId': '4303724329',
          'appMenuCode': '960813',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/basicCommonQuery',
          'appMenuTypeCode': '256053',
          'appMenuName': '首页常用查询',
          'appMenuList': []
        }, {
          'appMenuId': '4303724333',
          'appMenuCode': '960814',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/basicIntegratedQuery',
          'appMenuTypeCode': '256053',
          'appMenuName': '首页综合查询',
          'appMenuList': []
        }, {
          'appMenuId': '4303724337',
          'appMenuCode': '960815',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/basicAdvancedQuery',
          'appMenuTypeCode': '256053',
          'appMenuName': '首页高级查询',
          'appMenuList': []
        }, {
          'appMenuId': '4303724341',
          'appMenuCode': '958591',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/hQualityControl',
          'appMenuTypeCode': '256053',
          'appMenuName': '病案质控',
          'appMenuList': [
            {
              'appMenuId': '4303724345',
              'appMenuCode': '958592',
              'appMenuRelativeUri': 'web-medical-archive-qc/#/hQualityControl/needToDo',
              'appMenuTypeCode': '872106',
              'appMenuName': '待质控',
              'appMenuList': []
            }, {
              'appMenuId': '4303724349',
              'appMenuCode': '958593',
              'appMenuRelativeUri': 'web-medical-archive-qc/#/hQualityControl/repulsed',
              'appMenuTypeCode': '872106',
              'appMenuName': '已打回',
              'appMenuList': []
            }, {
              'appMenuId': '82410350706704385',
              'appMenuCode': '399000025',
              'appMenuRelativeUri': 'web-medical-archive-qc/#/hQualityControl/uncoded',
              'appMenuTypeCode': '872106',
              'appMenuName': '首页待编码',
              'appMenuList': []
            }, {
              'appMenuId': '82410436606050305',
              'appMenuCode': '399000026',
              'appMenuRelativeUri': 'web-medical-archive-qc/#/hQualityControl/noEntry',
              'appMenuTypeCode': '872106',
              'appMenuName': '首页待录入',
              'appMenuList': []
            }, {
              'appMenuId': '4303724353',
              'appMenuCode': '958594',
              'appMenuRelativeUri': 'web-medical-archive-qc/#/hQualityControl/completed',
              'appMenuTypeCode': '872106',
              'appMenuName': '已完成',
              'appMenuList': []
            }, {
              'appMenuId': '4303724357',
              'appMenuCode': '958595',
              'appMenuRelativeUri': 'web-medical-archive-qc/#/hQualityControl/uncommitted',
              'appMenuTypeCode': '872106',
              'appMenuName': '医生未提交',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '4303724361',
          'appMenuCode': '960816',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/hQualityQuery',
          'appMenuTypeCode': '256053',
          'appMenuName': '质控情况查询',
          'appMenuList': []
        }, {
          'appMenuId': '4303724365',
          'appMenuCode': '960817',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/hQualityProblem',
          'appMenuTypeCode': '256053',
          'appMenuName': '质控问题回复',
          'appMenuList': []
        }, {
          'appMenuId': '4303724369',
          'appMenuCode': '960818',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/revokeApplication',
          'appMenuTypeCode': '256053',
          'appMenuName': '医生撤销首页审批',
          'appMenuList': []
        }, {
          'appMenuId': '4303724373',
          'appMenuCode': '960819',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/specialAudit',
          'appMenuTypeCode': '256053',
          'appMenuName': '首页问题特批',
          'appMenuList': []
        }, {
          'appMenuId': '4303724377',
          'appMenuCode': '960820',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/paperless/medicalRecordArchiving',
          'appMenuTypeCode': '256053',
          'appMenuName': '电子病案归档',
          'appMenuList': []
        }, {
          'appMenuId': '4303724381',
          'appMenuCode': '960821',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256053',
          'appMenuName': '撤销归档审批',
          'appMenuList': []
        }, {
          'appMenuId': '4303724385',
          'appMenuCode': '960822',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256053',
          'appMenuName': '电子病案封存',
          'appMenuList': []
        }, {
          'appMenuId': '4303724389',
          'appMenuCode': '960823',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '查询分析',
          'appMenuList': [
            {
              'appMenuId': '4303724393',
              'appMenuCode': '958596',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '首页质控分析',
              'appMenuList': [
                {
                  'appMenuId': '4303724397',
                  'appMenuCode': '958597',
                  'appMenuRelativeUri': 'web-medical-archive-qc/#/qcProblemSummary',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '质控问题汇总',
                  'appMenuList': []
                }, {
                  'appMenuId': '82239877014908929',
                  'appMenuCode': '399000004',
                  'appMenuRelativeUri': 'web-medical-archive-qc/#/qcRanking',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '质控排名分析',
                  'appMenuList': [
                    {
                      'appMenuId': '82368163331985409',
                      'appMenuCode': '399000005',
                      'appMenuRelativeUri': 'web-medical-archive-qc/#/qcRanking/scoreRanking',
                      'appMenuTypeCode': '872106',
                      'appMenuName': '质控评分排名',
                      'appMenuList': []
                    }, {
                      'appMenuId': '82368335130677248',
                      'appMenuCode': '399000006',
                      'appMenuRelativeUri': 'web-medical-archive-qc/#/qcRanking/problemRanking',
                      'appMenuTypeCode': '872106',
                      'appMenuName': '质控问题排名',
                      'appMenuList': []
                    }, {
                      'appMenuId': '82368386670284801',
                      'appMenuCode': '399000007',
                      'appMenuRelativeUri': 'web-medical-archive-qc/#/qcRanking/reworkRanking',
                      'appMenuTypeCode': '872106',
                      'appMenuName': '质控返修排名',
                      'appMenuList': []
                    }
                  ]
                }, {
                  'appMenuId': '4303724453',
                  'appMenuCode': '958611',
                  'appMenuRelativeUri': 'web-medical-archive-qc/#/qcProgressTracking',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '质控进度跟踪',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724457',
                  'appMenuCode': '958612',
                  'appMenuRelativeUri': 'web-medical-archive-qc/#/qcWorkloadAnalysis',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '质控工作量分析',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724437',
                  'appMenuCode': '958607',
                  'appMenuRelativeUri': 'web-medical-archive-qc/#/qcTrend',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '质控趋势分析',
                  'appMenuList': [
                    {
                      'appMenuId': '4303724441',
                      'appMenuCode': '958608',
                      'appMenuRelativeUri': 'web-medical-archive-qc/#/qcTrend/scoreTrend',
                      'appMenuTypeCode': '872106',
                      'appMenuName': '质控评分趋势',
                      'appMenuList': []
                    }, {
                      'appMenuId': '4303724445',
                      'appMenuCode': '958609',
                      'appMenuRelativeUri': 'web-medical-archive-qc/#/qcTrend/problemTrend',
                      'appMenuTypeCode': '872106',
                      'appMenuName': '质控问题趋势',
                      'appMenuList': []
                    }, {
                      'appMenuId': '4303724449',
                      'appMenuCode': '958610',
                      'appMenuRelativeUri': 'web-medical-archive-qc/#/qcTrend/reworkTrend',
                      'appMenuTypeCode': '872106',
                      'appMenuName': '质控返修趋势',
                      'appMenuList': []
                    }
                  ]
                }, {
                  'appMenuId': '82372189863825408',
                  'appMenuCode': '399000008',
                  'appMenuRelativeUri': 'web-medical-archive-qc/#/qcProblemDistribution',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '质控问题分布',
                  'appMenuList': [
                    {
                      'appMenuId': '82372486216568833',
                      'appMenuCode': '399000011',
                      'appMenuRelativeUri': 'web-medical-archive-qc/#/qcProblemDistribution/problemDistribution',
                      'appMenuTypeCode': '872106',
                      'appMenuName': '质控问题分布',
                      'appMenuList': []
                    }, {
                      'appMenuId': '82372539903660032',
                      'appMenuCode': '399000012',
                      'appMenuRelativeUri': 'web-medical-archive-qc/#/qcProblemDistribution/codeDistribution',
                      'appMenuTypeCode': '872106',
                      'appMenuName': '质控问题编码分布',
                      'appMenuList': []
                    }, {
                      'appMenuId': '82372312270393345',
                      'appMenuCode': '399000010',
                      'appMenuRelativeUri': 'web-medical-archive-qc/#/qcProblemDistribution/qcRuleDistribution',
                      'appMenuTypeCode': '872106',
                      'appMenuName': '质控评分规则分布',
                      'appMenuList': []
                    }, {
                      'appMenuId': '82372256435818496',
                      'appMenuCode': '399000009',
                      'appMenuRelativeUri': 'web-medical-archive-qc/#/qcProblemDistribution/qcItemDistribution',
                      'appMenuTypeCode': '872106',
                      'appMenuName': '质控评分项分布',
                      'appMenuList': []
                    }
                  ]
                }
              ]
            }
          ]
        }, {
          'appMenuId': '4303724465',
          'appMenuCode': '960824',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '系统管理',
          'appMenuList': [
            {
              'appMenuId': '4303724469',
              'appMenuCode': '960825',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '基础设置',
              'appMenuList': [
                {
                  'appMenuId': '82931149851082753',
                  'appMenuCode': '399000028',
                  'appMenuRelativeUri': 'webui-admin-mdm/#/businessUnit',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '业务单元设置',
                  'appMenuList': []
                }, {
                  'appMenuId': '105374739782477825',
                  'appMenuCode': '399202375',
                  'appMenuRelativeUri': 'webui-admin-mdm/#/department',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '行政科室设置',
                  'appMenuList': []
                }, {
                  'appMenuId': '82931188505788417',
                  'appMenuCode': '399000029',
                  'appMenuRelativeUri': 'webui-admin-mdm/#/person',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '员工设置',
                  'appMenuList': []
                }, {
                  'appMenuId': '82931216423075841',
                  'appMenuCode': '399000030',
                  'appMenuRelativeUri': 'webui-admin-mdm/#/role',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '角色设置',
                  'appMenuList': []
                }, {
                  'appMenuId': '105374924466071553',
                  'appMenuCode': '399202376',
                  'appMenuRelativeUri': 'webui-admin-mdm/#/term',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '主数据术语',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724473',
                  'appMenuCode': '960826',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/userDepartmentPermission',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '权限科室',
                  'appMenuList': []
                }, {
                  'appMenuId': '82420128199753729',
                  'appMenuCode': '399000027',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/enteringProcess',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '病案首页工作流程',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724477',
                  'appMenuCode': '960827',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/medicalRecordDepartment',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '病案统计科室',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724481',
                  'appMenuCode': '960828',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/aging',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '病案处理时效',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724485',
                  'appMenuCode': '960829',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/medicalRecordParam',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '系统参数',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724489',
                  'appMenuCode': '960830',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/reasonSetting',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '病案原因',
                  'appMenuList': []
                }
              ]
            }, {
              'appMenuId': '4303724493',
              'appMenuCode': '960831',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '首页质控设置',
              'appMenuList': [
                {
                  'appMenuId': '4303724497',
                  'appMenuCode': '960832',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/hScore',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '质控评分项',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724501',
                  'appMenuCode': '960833',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/hQualityProcess',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '质控场景',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724505',
                  'appMenuCode': '958623',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/problemTemplate',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '质控问题模板',
                  'appMenuList': []
                }
              ]
            }, {
              'appMenuId': '4303724509',
              'appMenuCode': '958624',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '病案首页设置',
              'appMenuList': [
                {
                  'appMenuId': '4303724513',
                  'appMenuCode': '958625',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/projectList',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '首页控件',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724517',
                  'appMenuCode': '958626',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/templateMaintain',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '首页模板',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724521',
                  'appMenuCode': '958627',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/isUseTem',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '首页启用模板',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724525',
                  'appMenuCode': '958628',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/entrySettings',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '首页录入',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724529',
                  'appMenuCode': '958630',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/dictionaryVersion',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '首页字典版本',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724533',
                  'appMenuCode': '958631',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/interfaceType',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '首页接口类型',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724537',
                  'appMenuCode': '958632',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/dictionaryConfig',
                  'appMenuTypeCode': '256053',
                  'appMenuName': 'HIS首页字典',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724541',
                  'appMenuCode': '958633',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/HISDictionaryComparison',
                  'appMenuTypeCode': '256053',
                  'appMenuName': 'HIS首页字典对照',
                  'appMenuList': []
                }, {
                  'appMenuId': '95936409533716481',
                  'appMenuCode': '399015319',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/IHGradeComparison',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '切口愈合等级对照',
                  'appMenuList': []
                }
              ]
            }, {
              'appMenuId': '4303724545',
              'appMenuCode': '960834',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '病案归档设置',
              'appMenuList': [
                {
                  'appMenuId': '4303724549',
                  'appMenuCode': '960835',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/businessSystem',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '业务系统设置',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724553',
                  'appMenuCode': '960836',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/fileRepealAuditProcess',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '撤销归档审批流程设置',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724561',
                  'appMenuCode': '960838',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/directorySetting',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '病案文档目录设置',
                  'appMenuList': []
                }, {
                  'appMenuId': '4303724565',
                  'appMenuCode': '960839',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/catalogComparison',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '文件目录对照设置',
                  'appMenuList': []
                }, {
                  'appMenuId': '96135848487589889',
                  'appMenuCode': '399015330',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/fileAuditProblem',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '归档审核问题设置',
                  'appMenuList': []
                }, {
                  'appMenuId': '96135895732230145',
                  'appMenuCode': '399015331',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/integrityChecking',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '完整性校验设置',
                  'appMenuList': []
                }, {
                  'appMenuId': '96135930091968513',
                  'appMenuCode': '399015332',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/specialCaseTag',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '特殊病历标记设置',
                  'appMenuList': []
                }, {
                  'appMenuId': '96135968746674176',
                  'appMenuCode': '399015333',
                  'appMenuRelativeUri': 'url TODO',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '归档流程设置',
                  'appMenuList': []
                }
              ]
            }, {
              'appMenuId': '108895758317744128',
              'appMenuCode': '399207610',
              'appMenuRelativeUri': null,
              'appMenuTypeCode': '256051',
              'appMenuName': '首页查询设置',
              'appMenuList': [
                {
                  'appMenuId': '108895973066108928',
                  'appMenuCode': '399207611',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/homePageQueryFields',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '查询字段',
                  'appMenuList': []
                }, {
                  'appMenuId': '108896016015781888',
                  'appMenuCode': '399207612',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/homePageQueryModules',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '查询模块',
                  'appMenuList': []
                }, {
                  'appMenuId': '108896069702873088',
                  'appMenuCode': '399207613',
                  'appMenuRelativeUri': 'web-admin-medical-archive/#/homePageQueryResTemp',
                  'appMenuTypeCode': '256053',
                  'appMenuName': '首页结果模板',
                  'appMenuList': []
                }
              ]
            }
          ]
        }, {
          'appMenuId': '110939138400940033',
          'appMenuCode': '399210375',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/homeSpotcheck/codeSpotcheck',
          'appMenuTypeCode': '256053',
          'appMenuName': '首页编码抽查',
          'appMenuList': []
        }, {
          'appMenuId': '110939174908162049',
          'appMenuCode': '399210376',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/homeSpotcheck/spotcheckResults',
          'appMenuTypeCode': '256053',
          'appMenuName': '首页抽查结果',
          'appMenuList': []
        }, {
          'appMenuId': '111539383702876160',
          'appMenuCode': '399210583',
          'appMenuRelativeUri': 'web-medical-archive-qc/#/paperless/paperlessSpecialTag',
          'appMenuTypeCode': '256053',
          'appMenuName': '特殊病历标记',
          'appMenuList': []
        }
      ]
    }, {
      'appSystemId': '4303749149',
      'appSystemName': '医院业务管理系统（portal）',
      'appSystemPicUrl': 'c:\\',
      'appSystemRelativeUri': null,
      'appMenuList': [
        {
          'appMenuId': '80756401686728705',
          'appMenuCode': '399000002',
          'appMenuRelativeUri': ' ',
          'appMenuTypeCode': '256053',
          'appMenuName': '修改密码',
          'appMenuList': []
        }
      ]
    }, {
      'appSystemId': '4300000016',
      'appSystemName': '门诊医生站',
      'appSystemPicUrl': 'c:\\',
      'appSystemRelativeUri': 'outpatient',
      'appMenuList': [
        {
          'appMenuId': '4300200106',
          'appMenuCode': '256862',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256053',
          'appMenuName': '门诊医生站主菜单',
          'appMenuList': []
        }
      ]
    }, {
      'appSystemId': '4303595742',
      'appSystemName': '住院护士站',
      'appSystemPicUrl': 'c:\\',
      'appSystemRelativeUri': 'web-carnation',
      'appMenuList': [
        {
          'appMenuId': '90005955268360193',
          'appMenuCode': '399010039',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '床位卡',
          'appMenuList': [
            {
              'appMenuId': '90006026135320577',
              'appMenuCode': '399010040',
              'appMenuRelativeUri': 'web-carnation/workbench/dischargeOutArea',
              'appMenuTypeCode': '256053',
              'appMenuName': '患者出区',
              'appMenuList': []
            }, {
              'appMenuId': '90006092707313664',
              'appMenuCode': '399010041',
              'appMenuRelativeUri': 'web-carnation/workbench/dischargeRecallArea',
              'appMenuTypeCode': '256053',
              'appMenuName': '出区召回',
              'appMenuList': []
            }, {
              'appMenuId': '90006195786528769',
              'appMenuCode': '399010042',
              'appMenuRelativeUri': 'web-carnation/workbench/dischargeChangeArea',
              'appMenuTypeCode': '256053',
              'appMenuName': '转科转区',
              'appMenuList': []
            }, {
              'appMenuId': '94096432701009920',
              'appMenuCode': '399014926',
              'appMenuRelativeUri': '?handler=coverBed',
              'appMenuTypeCode': '256053',
              'appMenuName': '包床',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '90006262358521856',
          'appMenuCode': '399010043',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '病区工作台',
          'appMenuList': [
            {
              'appMenuId': '90020465817696256',
              'appMenuCode': '399010046',
              'appMenuRelativeUri': 'web-carnation/workbench/dischargeOutArea',
              'appMenuTypeCode': '256053',
              'appMenuName': '患者出区',
              'appMenuList': []
            }, {
              'appMenuId': '90020607551617025',
              'appMenuCode': '399010047',
              'appMenuRelativeUri': 'web-carnation/workbench/dischargeRecallArea',
              'appMenuTypeCode': '256053',
              'appMenuName': '出区召回',
              'appMenuList': []
            }, {
              'appMenuId': '90022130117523456',
              'appMenuCode': '399010048',
              'appMenuRelativeUri': 'web-carnation/workbench/dischargeChangeArea',
              'appMenuTypeCode': '256053',
              'appMenuName': '转科转区',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '108193273466810368',
          'appMenuCode': '399207267',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '物资管理',
          'appMenuList': [
            {
              'appMenuId': '108193696521089024',
              'appMenuCode': '399207268',
              'appMenuRelativeUri': 'webui-inpatient-collectmedicine/#/drugReturnApply',
              'appMenuTypeCode': '256053',
              'appMenuName': '退药申请',
              'appMenuList': []
            }
          ]
        }
      ]
    }, {
      'appSystemId': '92387828168931329',
      'appSystemName': '药品进销存',
      'appSystemPicUrl': null,
      'appSystemRelativeUri': 'web-psi-pharmacy',
      'appMenuList': [
        {
          'appMenuId': '92388289877915648',
          'appMenuCode': '399011345',
          'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/openingstock/index',
          'appMenuTypeCode': '256053',
          'appMenuName': '期初库存',
          'appMenuList': []
        }, {
          'appMenuId': '92388654950135809',
          'appMenuCode': '399011346',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '请调管理',
          'appMenuList': [
            {
              'appMenuId': '92389026464806913',
              'appMenuCode': '399011347',
              'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/adjuststock/adjustapply',
              'appMenuTypeCode': '256053',
              'appMenuName': '请调申请',
              'appMenuList': []
            }, {
              'appMenuId': '92389084446865408',
              'appMenuCode': '399011348',
              'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/adjuststock/adjustout',
              'appMenuTypeCode': '256053',
              'appMenuName': '请调出库',
              'appMenuList': []
            }, {
              'appMenuId': '92389127396538368',
              'appMenuCode': '399011349',
              'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/adjuststock/adjustin',
              'appMenuTypeCode': '256053',
              'appMenuName': '请调入库',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '92389166051244033',
          'appMenuCode': '399011350',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '入库管理',
          'appMenuList': [
            {
              'appMenuId': '92389206853433345',
              'appMenuCode': '399011351',
              'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/stockin/reportoverflowin',
              'appMenuTypeCode': '256053',
              'appMenuName': '报溢入库',
              'appMenuList': []
            }, {
              'appMenuId': '92389243360655360',
              'appMenuCode': '399011352',
              'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/stockin/departmentreturn',
              'appMenuTypeCode': '256053',
              'appMenuName': '部门退回',
              'appMenuList': []
            }, {
              'appMenuId': '92389284162844673',
              'appMenuCode': '399011353',
              'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/stockin/staffreturn',
              'appMenuTypeCode': '256053',
              'appMenuName': '职工退回',
              'appMenuList': []
            }, {
              'appMenuId': '92389335702452224',
              'appMenuCode': '399011354',
              'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/stockin/directin',
              'appMenuTypeCode': '256053',
              'appMenuName': '直接入库',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '92389451666569217',
          'appMenuCode': '399011355',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '出库管理',
          'appMenuList': [
            {
              'appMenuId': '92389483878823936',
              'appMenuCode': '399011356',
              'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/stockout/reportdamageout',
              'appMenuTypeCode': '256053',
              'appMenuName': '报损出库',
              'appMenuList': []
            }, {
              'appMenuId': '92389522533529600',
              'appMenuCode': '399011357',
              'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/stockout/departmentout',
              'appMenuTypeCode': '256053',
              'appMenuName': '部门出库',
              'appMenuList': []
            }, {
              'appMenuId': '92389563335718912',
              'appMenuCode': '399011358',
              'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/stockout/staffout',
              'appMenuTypeCode': '256053',
              'appMenuName': '职工出库',
              'appMenuList': []
            }, {
              'appMenuId': '92389623465261057',
              'appMenuCode': '399011359',
              'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/stockout/directout',
              'appMenuTypeCode': '256053',
              'appMenuName': '直接出库',
              'appMenuList': []
            }, {
              'appMenuId': '92389662119966720',
              'appMenuCode': '399011360',
              'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/stockout/sampleout',
              'appMenuTypeCode': '256053',
              'appMenuName': '抽样出库',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '92389722249508865',
          'appMenuCode': '399011361',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '药品调价',
          'appMenuList': [
            {
              'appMenuId': '92389788821501953',
              'appMenuCode': '399011362',
              'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/drugadjust/drugadjustreporter',
              'appMenuTypeCode': '256053',
              'appMenuName': '调价通知',
              'appMenuList': []
            }, {
              'appMenuId': '92389846803560449',
              'appMenuCode': '399011363',
              'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/drugadjust/drugadjustbill',
              'appMenuTypeCode': '256053',
              'appMenuName': '调价账单',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '92389958472710145',
          'appMenuCode': '399011364',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '药品盘点',
          'appMenuList': [
            {
              'appMenuId': '92389994979932161',
              'appMenuCode': '399011365',
              'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/drugcheck/drugcheckrecord',
              'appMenuTypeCode': '256053',
              'appMenuName': '盘点录入',
              'appMenuList': []
            }, {
              'appMenuId': '92390029339670529',
              'appMenuCode': '399011366',
              'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/drugcheck/drugcheckaccount',
              'appMenuTypeCode': '256053',
              'appMenuName': '盘点账存单',
              'appMenuList': []
            }, {
              'appMenuId': '92390065846892544',
              'appMenuCode': '399011367',
              'appMenuRelativeUri': 'web-psi-pharmacy/#/psimanagement/drugcheck/drugcheckapprove',
              'appMenuTypeCode': '256053',
              'appMenuName': '盘点审核',
              'appMenuList': []
            }
          ]
        }
      ]
    }, {
      'appSystemId': '80719641117485057',
      'appSystemName': '数据质量管理系统',
      'appSystemPicUrl': null,
      'appSystemRelativeUri': 'web-data-quality/#/dataquality/maindataquality',
      'appMenuList': [
        {
          'appMenuId': '102986284866803712',
          'appMenuCode': '399197641',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '质量监控',
          'appMenuList': [
            {
              'appMenuId': '102986347143829505',
              'appMenuCode': '399197643',
              'appMenuRelativeUri': 'web-data-quality/#/dataquality/maindataquality',
              'appMenuTypeCode': '256053',
              'appMenuName': '主数据质量',
              'appMenuList': []
            }
          ]
        }, {
          'appMenuId': '102986306341640192',
          'appMenuCode': '399197642',
          'appMenuRelativeUri': null,
          'appMenuTypeCode': '256051',
          'appMenuName': '规则管理',
          'appMenuList': [
            {
              'appMenuId': '102986385798535168',
              'appMenuCode': '399197644',
              'appMenuRelativeUri': 'web-data-quality/#/rulemmanage/checkrulemanage',
              'appMenuTypeCode': '256053',
              'appMenuName': '检验规则管理',
              'appMenuList': []
            }
          ]
        }
      ]
    }, {
      'appSystemId': '4303253901',
      'appSystemName': '账户管理系统',
      'appSystemPicUrl': 'c:\\',
      'appSystemRelativeUri': 'web-account-management',
      'appMenuList': [
        {
          'appMenuId': '106667170654810113',
          'appMenuCode': '399203507',
          'appMenuRelativeUri': 'web-account-management/#/acctManagement',
          'appMenuTypeCode': '256053',
          'appMenuName': '帐户管理',
          'appMenuList': []
        }, {
          'appMenuId': '106667359633371137',
          'appMenuCode': '399203508',
          'appMenuRelativeUri': 'web-account-management/#/rechargeRefund',
          'appMenuTypeCode': '256053',
          'appMenuName': '充值退卡',
          'appMenuList': []
        }
      ]
    }, {
      'appSystemId': '4303595739',
      'appSystemName': '住院医生站',
      'appSystemPicUrl': 'c:\\',
      'appSystemRelativeUri': 'web-jindal',
      'appMenuList': [
        {
          'appMenuId': '88710311807494145',
          'appMenuCode': '399001111',
          'appMenuRelativeUri': '·',
          'appMenuTypeCode': '256053',
          'appMenuName': '住院医生站主菜单',
          'appMenuList': []
        }
      ]
    }, {
      'appSystemId': '4302708202',
      'appSystemName': '门诊费用管理',
      'appSystemPicUrl': 'c:\\',
      'appSystemRelativeUri': 'fee-management-outp',
      'appMenuList': [
        {
          'appMenuId': '4302708264',
          'appMenuCode': '869496',
          'appMenuRelativeUri': '/#/feeCompare',
          'appMenuTypeCode': '256053',
          'appMenuName': '费用对比',
          'appMenuList': []
        }, {
          'appMenuId': '4302708265',
          'appMenuCode': '869497',
          'appMenuRelativeUri': '/#/orderTracking',
          'appMenuTypeCode': '256053',
          'appMenuName': '订单查询',
          'appMenuList': []
        }, {
          'appMenuId': '4303155806',
          'appMenuCode': '958109',
          'appMenuRelativeUri': 'outpCharge',
          'appMenuTypeCode': '256053',
          'appMenuName': '门诊收费',
          'appMenuList': []
        }, {
          'appMenuId': '4303155810',
          'appMenuCode': '958110',
          'appMenuRelativeUri': 'outpRefund',
          'appMenuTypeCode': '256053',
          'appMenuName': '门诊退费',
          'appMenuList': []
        }, {
          'appMenuId': '104447832152909825',
          'appMenuCode': '399201997',
          'appMenuRelativeUri': '/#/receiptPrinting',
          'appMenuTypeCode': '256053',
          'appMenuName': '单据打印',
          'appMenuList': []
        }
      ]
    }
  ],
  'appid': '4126',
  'traceid': '9af65d6347de983e',
  'hostip': '172.16.6.29'
}
