export default [
  {
    'appSystemId': '1',
    'appSystemCode': '959608',
    'appSystemName': '账户管理系统',
    'appSystemRelativeUri': 'web-account-management',
    'appSystemPicUrl': 'c:\\',
    'pareAppSystemCode': null,
    'pareAppSystemName': null,
    appMenuList: [
      {
        'appMenuId': '430270826411',
        'activatedAt': '2020-04-24 15:18:57',
        'appMenuCode': '869496',
        appMenuName: '账户-1',
        'appMenuLevel': null,
        'appMenuRelativeUri': '/feeCompare',
        'appMenuTypeCode': '256053',
        'appOpTypeCode': '256484',
        'appPermissionId': '4302708266',
        'appPermissionTypeCode': '256489',
        'deactivatedAt': null,
        'pareAppMenuCode': null,
        port: 3000
      }, {
        'appMenuId': '4302708265',
        'activatedAt': '2020-04-24 15:18:57',
        'appMenuCode': '869497',
        'appMenuLevel': null,
        appMenuName: '账户-2',
        'appMenuRelativeUri': '/#/orderTracking',
        'appMenuTypeCode': '256053',
        'appOpTypeCode': '256484',
        'appPermissionId': '4302708267',
        'appPermissionTypeCode': '256489',
        'deactivatedAt': null,
        'pareAppMenuCode': null,
        port: 3001
      }
    ]

  }, {
    'appSystemId': '2',
    'appSystemCode': '951678',
    'appSystemName': '住院护士站',
    'appSystemRelativeUri': 'web-carnation',
    'appSystemPicUrl': 'c:\\',
    'pareAppSystemCode': null,
    'pareAppSystemName': null,
    appMenuList: [
      {
        'appMenuId': '4302708264',
        'activatedAt': '2020-04-24 15:18:57',
        'appMenuCode': '869496',
        appMenuName: '住院-1',
        'appMenuLevel': null,
        'appMenuRelativeUri': '/wwwww',
        'appMenuTypeCode': '256053',
        'appOpTypeCode': '256484',
        'appPermissionId': '4302708266',
        'appPermissionTypeCode': '256489',
        'deactivatedAt': null,
        'pareAppMenuCode': null,
        port: 1001
      }, {
        'appMenuId': '4302708265222',
        'activatedAt': '2020-04-24 15:18:57',
        'appMenuCode': '869497',
        'appMenuLevel': null,
        appMenuName: '住院-2',
        'appMenuRelativeUri': '/#/3ffff',
        'appMenuTypeCode': '256053',
        'appOpTypeCode': '256484',
        'appPermissionId': '4302708267',
        'appPermissionTypeCode': '256489',
        'deactivatedAt': null,
        'pareAppMenuCode': null,
        port: 1002
      }
    ]
  }, {
    'appSystemId': '3',
    'appSystemCode': '958576',
    'appSystemName': '病案系统',
    'appSystemRelativeUri': 'web-medical-archive-portal/index/#/toDoList',
    'appSystemPicUrl': 'c:\\',
    'pareAppSystemCode': null,
    'pareAppSystemName': null,
    appMenuList: [
      {
        'appMenuId': '430315580645',
        'activatedAt': '2020-04-24 15:18:57',
        'appMenuCode': '958109',
        'appMenuLevel': '0',
        appMenuName: '病案-1',
        'appMenuRelativeUri': 'outpCharge',
        'appMenuTypeCode': '256053',
        'appOpTypeCode': '256484',
        'appPermissionId': '4303155807',
        'appPermissionTypeCode': '256489',
        'deactivatedAt': null,
        'pareAppMenuCode': null,
        port: 3001
      }, {
        'appMenuId': '4303155810',
        'activatedAt': '2020-04-24 15:18:57',
        'appMenuCode': '958110',
        'appMenuLevel': '0',
        appMenuName: '病案-2',
        'appMenuRelativeUri': 'outpRefund',
        'appMenuTypeCode': '256053',
        'appOpTypeCode': '256484',
        'appPermissionId': '4303155811',
        'appPermissionTypeCode': '256489',
        'deactivatedAt': null,
        'pareAppMenuCode': null,
        port: 3001
      }, {
        appMenuName: '病案-3',
        'appMenuId': '104447832152909825',
        'activatedAt': '2020-04-24 15:18:57',
        'appMenuCode': '399201997',
        'appMenuLevel': null,
        'appMenuRelativeUri': '/#/receiptPrinting',
        'appMenuTypeCode': '256053',
        'appOpTypeCode': '256483',
        'appPermissionId': '104447832152909825',
        'appPermissionTypeCode': '256489',
        'deactivatedAt': null,
        'pareAppMenuCode': null,
        port: 3005
      }
    ]
  }, {
    'appSystemId': '4302475966',
    'appSystemCode': '465362',
    'appSystemName': '门诊部管理',
    'appSystemRelativeUri': 'web-adt-outpatient/index',
    'appSystemPicUrl': null,
    'pareAppSystemCode': null,
    'pareAppSystemName': null
  }, {
    'appSystemId': '4302475968',
    'appSystemCode': '465364',
    'appSystemName': '门诊挂号',
    'appSystemRelativeUri': 'web-adt-outpatient/regiester',
    'appSystemPicUrl': 'c:\\',
    'pareAppSystemCode': null,
    'pareAppSystemName': null
  }, {
    'appSystemId': '4302475967',
    'appSystemCode': '465363',
    'appSystemName': '门诊预约',
    'appSystemRelativeUri': 'web-adt-outpatient/bookindex',
    'appSystemPicUrl': 'c:\\',
    'pareAppSystemCode': null,
    'pareAppSystemName': null
  }, {
    'appSystemId': '4302475969',
    'appSystemCode': '465365',
    'appSystemName': '患者管理',
    'appSystemRelativeUri': 'web-person-patient/index',
    'appSystemPicUrl': 'c:\\',
    'pareAppSystemCode': null,
    'pareAppSystemName': null
  }, {
    'appSystemId': '4303595739',
    'appSystemCode': '951677',
    'appSystemName': '住院医生站',
    'appSystemRelativeUri': 'web-jindal',
    'appSystemPicUrl': 'c:\\',
    'pareAppSystemCode': null,
    'pareAppSystemName': null
  }, {
    'appSystemId': '4300000014',
    'appSystemCode': '256493',
    'appSystemName': '别名',
    'appSystemRelativeUri': null,
    'appSystemPicUrl': 'c:\\',
    'pareAppSystemCode': null,
    'pareAppSystemName': null
  }, {
    'appSystemId': '80719641117485057',
    'appSystemCode': '399000001',
    'appSystemName': '数据质量管理系统',
    'appSystemRelativeUri': 'web-data-quality/#/dataquality/maindataquality',
    'appSystemPicUrl': null,
    'pareAppSystemCode': null,
    'pareAppSystemName': null
  }, {
    'appSystemId': '92387828168931329',
    'appSystemCode': '399011344',
    'appSystemName': '药品进销存',
    'appSystemRelativeUri': 'web-psi-pharmacy',
    'appSystemPicUrl': null,
    'pareAppSystemCode': null,
    'pareAppSystemName': null
  }, {
    'appSystemId': '4300000016',
    'appSystemCode': '256495',
    'appSystemName': '西安四院别名测试',
    'appSystemRelativeUri': 'outpatient',
    'appSystemPicUrl': 'c:\\',
    'pareAppSystemCode': null,
    'pareAppSystemName': null
  }, {
    'appSystemId': '4300000015',
    'appSystemCode': '256494',
    'appSystemName': '测试别名',
    'appSystemRelativeUri': 'web-admin-mdm-framework/#/master-data',
    'appSystemPicUrl': 'c:\\',
    'pareAppSystemCode': null,
    'pareAppSystemName': null
  }, {
    'appSystemId': '4303749149',
    'appSystemCode': '973265',
    'appSystemName': '医院业务管理系统（portal）',
    'appSystemRelativeUri': null,
    'appSystemPicUrl': 'c:\\',
    'pareAppSystemCode': null,
    'pareAppSystemName': null
  }, {
    'appSystemId': '4302694254',
    'appSystemCode': '869474',
    'appSystemName': '票据管理',
    'appSystemRelativeUri': 'web-invoice-management',
    'appSystemPicUrl': 'c:\\',
    'pareAppSystemCode': null,
    'pareAppSystemName': null
  }, {
    'appSystemId': '108030805591420928',
    'appSystemCode': '399207237',
    'appSystemName': '门诊护士站',
    'appSystemRelativeUri': 'web-print-center/index',
    'appSystemPicUrl': null,
    'pareAppSystemCode': null,
    'pareAppSystemName': null
  }, {
    'appSystemId': '4302489029',
    'appSystemCode': '862225',
    'appSystemName': '收费系统',
    'appSystemRelativeUri': null,
    'appSystemPicUrl': 'c:\\',
    'pareAppSystemCode': null,
    'pareAppSystemName': null
  }, {
    'appSystemId': '4303920397',
    'appSystemCode': '399000293',
    'appSystemName': '门户配置',
    'appSystemRelativeUri': 'web-portal-admin',
    'appSystemPicUrl': 'c:\\',
    'pareAppSystemCode': null,
    'pareAppSystemName': null
  }, {
    'appSystemId': '4302708202',
    'appSystemCode': '869495',
    'appSystemName': '门诊费用管理',
    'appSystemRelativeUri': 'fee-management-outp',
    'appSystemPicUrl': 'c:\\',
    'pareAppSystemCode': null,
    'pareAppSystemName': null
  }
]
